# Generated by Django 5.1 on 2025-10-15 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Membresia',
            fields=[
                ('id_membresia', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('costo_mensual', models.DecimalField(decimal_places=2, max_digits=8)),
                ('acceso_limitado', models.BooleanField(default=False)),
                ('acceso_entrenador', models.BooleanField(default=False)),
            ],
        ),
    ]
